const answersConfig = [
    { title: "linux:", file: "linux/no-file.html"},
    { title: "جواب درس 1: آشنایی با لینوکس و اوبونتو", file: "linux/answer-linux-intro.html" },
    { title: "درس 2 تمرینی ندارد", file: "linux/no-file.html"},
    { title: "جواب درس 3: آشنایی با ترمینال", file: "linux/answer-linux-terminal-intro.html" },
    { title: "جواب درس 4: دستور pwd", file: "linux/answer-linux-command-pwd.html" },
    { title: "جواب درس 5: دستور ls", file: "linux/answer-linux-command-ls.html" },
    { title: "جواب درس 6: دستور cd", file: "linux/answer-linux-command-cd.html" },
    { title: "جواب درس 7: دستور mkdir", file: "linux/answer-linux-command-mkdir.html" },
    { title: "جواب درس 8: دستور touch", file: "linux/answer-linux-command-touch.html" },
    { title: "جواب درس 9: دستور rm", file: "linux/answer-linux-command-rm.html" },
    { title: "جواب درس 10: دستور cp", file: "linux/answer-linux-command-cp.html" },
    { title: "جواب درس 11: دستور mv", file: "linux/answer-linux-command-mv.html" },
    { title: "جواب درس 12: دستور cat", file: "linux/answer-linux-command-cat.html" },
    { title: "جواب درس 13: دستور less", file: "linux/answer-linux-command-less.html" },
    { title: "جواب درس 14: دستور echo", file: "linux/answer-linux-command-echo.html" },
    { title: "جواب درس 15: عملگرهای > و >>", file: "linux/answer-linux-redirect.html" },
    { title: "جواب درس 16: دستور man", file: "linux/answer-linux-command-man.html" },
    { title: "جواب درس 17: دستور sudo", file: "linux/answer-linux-command-sudo.html" },
    { title: "جواب درس 18: دستور apt – update & upgrade", file: "linux/answer-linux-command-apt-update-upgrade.html" },
    { title: "جواب درس 19: دستور apt – install & remove", file: "linux/answer-linux-command-apt-install-remove.html" },
    { title: "جواب درس 20: دستور chmod", file: "linux/answer-linux-command-chmod.html" },
    { title: "جواب درس 21: دستور chown", file: "linux/answer-linux-command-chown.html" },
    { title: "جواب درس 22: دستور ps", file: "linux/answer-linux-command-ps.html" },
    { title: "جواب درس 23: دستور kill", file: "linux/answer-linux-command-kill.html" },
    { title: "جواب درس 24: دستور grep", file: "linux/answer-linux-command-grep.html" },
    { title: "جواب درس 25: دستور find", file: "linux/answer-linux-command-find.html" },
    { title: "جواب درس 26: دستور tar", file: "linux/answer-linux-command-tar.html" },
    { title: "جواب درس 27: دستور zip", file: "linux/answer-linux-command-zip.html" },
    { title: "جواب درس 28: دستور ln", file: "linux/answer-linux-command-ln.html" },
    { title: "جواب درس 29: دستور alias", file: "linux/answer-linux-command-alias.html" },
    { title: "جواب درس 30: دستور history", file: "linux/answer-linux-command-history.html" },
    { title: "جواب درس 31: دستور systemctl", file: "linux/answer-linux-command-systemctl.html" },
    { title: "جواب درس 32: دستور cron و crontab", file: "linux/answer-linux-command-cron.html" },
    { title: "جواب درس 33: دستور whoami", file: "linux/answer-linux-command-whoami.html" },
    { title: "جواب درس 34: دستور id", file: "linux/answer-linux-command-id.html" },
    { title: "جواب درس 35: دستور uname", file: "linux/answer-linux-command-uname.html" },
    { title: "جواب درس 36: دستور uptime", file: "linux/answer-linux-command-uptime.html" },
    { title: "جواب درس 37: دستور free", file: "linux/answer-linux-command-free.html" },
    { title: "جواب درس 38: دستور df", file: "linux/answer-linux-command-df.html" },
    { title: "جواب درس 39: دستور du", file: "linux/answer-linux-command-du.html" },
    { title: "جواب درس 40: دستور top", file: "linux/answer-linux-command-top.html" },
    { title: "جواب درس 41: دستور htop", file: "linux/answer-linux-command-htop.html" },
    { title: "جواب درس 42: دستور ping", file: "linux/answer-linux-command-ping.html" },
    { title: "جواب درس 43: دستور curl", file: "linux/answer-linux-command-curl.html" },
    { title: "جواب درس 44: دستور wget", file: "linux/answer-linux-command-wget.html" },
    { title: "جواب درس 45: دستور ssh", file: "linux/answer-linux-command-ssh.html" },
    { title: "جواب درس 46: دستور scp", file: "linux/answer-linux-command-scp.html" },
    { title: "جواب درس 47: دستور rsync", file: "linux/answer-linux-command-rsync.html" },
    { title: "جواب درس 48: دستور netstat", file: "linux/answer-linux-command-netstat.html" },
    { title: "جواب درس 49: دستور ss", file: "linux/answer-linux-command-ss.html" },
    { title: "جواب درس 50: دستور ufw", file: "linux/answer-linux-command-ufw.html" },
    { title: "جواب درس 51: دستور dmesg", file: "linux/answer-linux-command-dmesg.html" }
]