const lessonsConfig = [
    { title: "آشنایی با لینوکس و اوبونتو", file: "linux-intro.html" },
    { title: "آشنایی با ترمینال", file: "linux-terminal-intro.html" },
    { title: "دستور pwd", file: "linux-command-pwd.html" },
    { title: "دستور ls", file: "linux-command-ls.html" },
    { title: "دستور cd", file: "linux-command-cd.html" },
    { title: "دستور mkdir", file: "linux-command-mkdir.html" },
    { title: "دستور touch", file: "linux-command-touch.html" },
    { title: "دستور rm", file: "linux-command-rm.html" },
    { title: "دستور cp", file: "linux-command-cp.html" },
    { title: "دستور mv", file: "linux-command-mv.html" },
    { title: "دستور cat", file: "linux-command-cat.html" },
    { title: "دستور less", file: "linux-command-less.html" },
    { title: "دستور echo", file: "linux-command-echo.html" },
    { title: "عملگرهای > و >>", file: "linux-redirect.html" },
    { title: "دستور man", file: "linux-command-man.html" },
    { title: "دستور sudo", file: "linux-command-sudo.html" },
    { title: "دستور apt – update & upgrade", file: "linux-command-apt-update-upgrade.html" },
    { title: "دستور apt – install & remove", file: "linux-command-apt-install-remove.html" },
    { title: "دستور chmod", file: "linux-command-chmod.html" },
    { title: "دستور chown", file: "linux-command-chown.html" },
    { title: "دستور ps", file: "linux-command-ps.html" },
    { title: "دستور kill", file: "linux-command-kill.html" },
    { title: "دستور grep", file: "linux-command-grep.html" },
    { title: "دستور find", file: "linux-command-find.html" },
    { title: "دستور tar", file: "linux-command-tar.html" },
    { title: "دستور zip", file: "linux-command-zip.html" },
    { title: "دستور ln", file: "linux-command-ln.html" },
    { title: "دستور alias", file: "linux-command-alias.html" },
    { title: "دستور history", file: "linux-command-history.html" },
    { title: "دستور systemctl", file: "linux-command-systemctl.html" },
    { title: "دستور cron و crontab", file: "linux-command-cron.html" },
    { title: "دستور whoami", file: "linux-command-whoami.html" },
    { title: "دستور id", file: "linux-command-id.html" },
    { title: "دستور uname", file: "linux-command-uname.html" },
    { title: "دستور uptime", file: "linux-command-uptime.html" },
    { title: "دستور free", file: "linux-command-free.html" },
    { title: "دستور df", file: "linux-command-df.html" },
    { title: "دستور du", file: "linux-command-du.html" },
    { title: "دستور top", file: "linux-command-top.html" },
    { title: "دستور htop", file: "linux-command-htop.html" },
    { title: "دستور ping", file: "linux-command-ping.html" },
    { title: "دستور curl", file: "linux-command-curl.html" },
    { title: "دستور wget", file: "linux-command-wget.html" },
    { title: "دستور ssh", file: "linux-command-ssh.html" },
    { title: "دستور scp", file: "linux-command-scp.html" },
    { title: "دستور rsync", file: "linux-command-rsync.html" },
    { title: "دستور netstat", file: "linux-command-netstat.html" },
    { title: "دستور ss", file: "linux-command-ss.html" },
    { title: "دستور ufw", file: "linux-command-ufw.html" },
    { title: "دستور dmesg", file: "linux-command-dmesg.html" }
]